name: grantscube_contracts
plugins:
  - name: solidity
  - name: notebook
  - name: etherscan

default_ecosystem: ethereum

ethereum:
  default_network: mainnet
  mainnet:
    default_provider: alchemy
